# Site settings
title: Neil Baxter
email: neilcbaxter@hotmail.com
description: "sports and industrial designer"
baseurl: ""
url: "http://www.neilcbaxter.com"
github_username:  neilcbaxter

# Build settings
markdown: kramdown
permalink: pretty
